### ISSUE TITLE
Deployment issues on Vercel

### ISSUE THREAD

**Issue by audvin** [contextco/context-node#38]
`pnpm install @contextco/context-node`

package.json
```
 "dependencies": {
    "@contextco/context-node": "^0.8.0",
```

see screenshot for deployments result on Vercel.
<img width="1147" alt="Screenshot 2024-03-29 at 11 04 56 AM" src="https://github.com/contextco/context-node/assets/1017880/418fa5dd-7117-4d16-8eec-59530a7fa74b">

**Comment by agamble** [comment]
Hey Audun, unfortunately we don't support this environment at the moment - it's a known issue and on the roadmap though!

Recommend using the [API directly](https://docs.context.ai/product-analytics/api-ingestion-methods) for now as a workaround.
